let strip2 = smartfeldAktoren.create(DigitalPin.P2, 60, NeoPixelMode.RGB)
let range = strip2.range(0, 4)
strip2.showColor(neopixel.colors(NeoPixelColors.Red))
basic.forever(function () {
    basic.pause(2000)
    strip2.setBrightness(50)
    strip2.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    strip2.setBrightness(0)
    strip2.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
})
