smartfeldAktoren.displayInit(128, 64)
basic.forever(function () {
    basic.pause(1000)
    smartfeldAktoren.displayWriteStr("Num")
    basic.pause(1000)
    smartfeldAktoren.displayWriteNum(0)
    basic.pause(1000)
    smartfeldAktoren.displayNewLine()
    basic.pause(1000)
    smartfeldAktoren.displayWriteNum(2)
    basic.pause(2000)
    smartfeldAktoren.displayWriteNum(5)
    basic.pause(2000)
    smartfeldAktoren.displayWriteStrNewLine("neu")
    basic.pause(2000)
    smartfeldAktoren.displayWriteNumNewLine(4)
    basic.pause(2000)
    smartfeldAktoren.displayWriteNum(65454165)
    basic.pause(2000)
})
